### ISSUE TITLE
Initialize Facebook's graph API 

### ISSUE THREAD

**Issue by pshishod2645** [pshishod2645/GOC-Website#1]

**Comment by abhinav72610** [comment]
@pshishod2645 would like to work on this..Can you brief me ??

**Comment by pshishod2645** [comment]
Hi @abhinav72610 I'd be closing this issue as I feel building our own tables for comments and all would be better than using facebook's api. 

Will you rather look into login and registration forms instead?

**Comment by abhinav72610** [comment]
Login and registration forms using flask-wtf ?

**Comment by pshishod2645** [comment]
Yes exactly. Wait I'll create a separate issue for it and assign it to you.
