### ISSUE TITLE
Blog submissions (Backend)

### ISSUE THREAD

**Issue by TheLethalCode** [pshishod2645/GOC-Website#12]
We need a mechanism for submitting blogs. Assume you receive a post request at "/submitBlog". We need a handler function that handles the post request. It should

1) verify the presence of all necessary data and metadata
2) insert it into the database properly while managing the accompanying tags as well
3) Reutrn success/failure status (the type of error, if it fails)

**Comment by rupraj-0406** [comment]
@TheLethalCode can you please assign me to this?

**Comment by anuratb** [comment]
I would like to try this one
