### ISSUE TITLE
Blog Schema

### ISSUE THREAD

**Issue by pshishod2645** [pshishod2645/GOC-Website#3]
Create the prototype for how a blog would look like.

**Comment by SubhradeepSS** [comment]
> 
> 
> Create the prototype for how a blog would look like.

The blog schema is needed to be defined using SQLAlchemy model right?

**Comment by pshishod2645** [comment]
Yes. Precisely.

**Comment by SubhradeepSS** [comment]
> 
> 
> Yes. Precisely.

Can u assign me this issue?

**Comment by pshishod2645** [comment]
@SubhradeepSS sure. Done!
