### ISSUE TITLE
Handling Blog List Requests Backend

### ISSUE THREAD

**Issue by TheLethalCode** [pshishod2645/GOC-Website#6]
Assuming we have a bunch of blogs, we need to list them out per request. Things to take care of

1) on a request ot "/blogs", all the existing blogs will be listed pagewise (with each page having a fixed number of blogs)
2) on a request of "/blogs?tags=...", the blogs with the particular tags as the argument have to be listed pagewise
3) A proper schema to store the existing blogs along with their tags (a json file?)

**Comment by SubhradeepSS** [comment]
> 
> 
> Assuming we have a bunch of blogs, we need to list them out per request. Things to take care of
> 
>     1. on a request ot "/blogs", all the existing blogs will be listed pagewise (with each page having a fixed number of blogs)
> 
>     2. on a request of "/blogs?tags=...", the blogs with the particular tags as the argument have to be listed pagewise
> 
>     3. A proper schema to store the existing blogs along with their tags (a json file?)

The blog schema is gonna be the same as we define the blog model using SQLAlchemy right?

**Comment by TheLethalCode** [comment]
Oh yeah, creating a database for the blogs is a good idea.

**Comment by SubhradeepSS** [comment]
@TheLethalCode I want to work on this issue. Can u assign me this?

**Comment by rupraj-0406** [comment]
@TheLethalCode can you assign me please?

**Comment by TheLethalCode** [comment]
Hey @rupraj-0406, it seems @SubhradeepSS  is already working on this. You might want to discuss this with him (you can use find each other in the slack workspace).

**Comment by rupraj-0406** [comment]
> Hey @rupraj-0406, it seems @SubhradeepSS is already working on this. You might want to discuss this with him (you can use find each other in the slack workspace).

Ok, sure I will do that  .
