### ISSUE TITLE
Login and Registration. 

### ISSUE THREAD

**Issue by pshishod2645** [pshishod2645/GOC-Website#9]
login form should have fields
```
username/email: 
password: 
```

Sign up form should have fields: 
```
gmail: 
username (cf): 
password: 
confirm password: 
```

The registration will be confirmed only user changes it email on code forces, with the same email as in here, and make it public, just for a while.

**Comment by pshishod2645** [comment]
@abhinav72610

**Comment by abhinav72610** [comment]
Couldn't get the last line .

**Comment by pshishod2645** [comment]
can you ping me on slack?

**Comment by pshishod2645** [comment]
Please join our communication channel here: https://join.slack.com/t/goc-website/shared_invite/zt-jqm8gtzm-vL2zlOSq6XDTkP27CFVpCQ

**Comment by pshishod2645** [comment]
What we want is, while signing up, we'll ask user for codeforces username and his email adddress. Once user does that and click on SignUp Button we'd open https://codeforces.com/settings/general in a new window and ask him to uncheck the box against `Hide contact information` and edit the same email address as he input here. Now that their email id is visible on codeforces, we can just make an api call and fetch their email id and profile pic (and will validate their email id against what they put here).

**Comment by abhinav72610** [comment]
Ok got it ,but how do we goona tell them to uncheck the box against hide contact information ??

**Comment by pshishod2645** [comment]
Hmm? I think on hitting signup redirect them to a dummy verification webpage that has please uncheck this box on popped up codeforces window would do ? What's the problem?

**Comment by abhinav72610** [comment]
Nothing, was just searching to optimize the problem will try to settle it soon.

**Comment by pshishod2645** [comment]
@abhinav72610  any updates on this? Shall I assign it to someone else ?

**Comment by abhinav72610** [comment]
i need help can i talk to you in slack ??

**Comment by pshishod2645** [comment]
Yes. I'm sorry for the late reply, actually, I get notifications from Github after some delay. Please ping me on slack.

**Comment by tsaraf20** [comment]
https://github.com/pshishod2645/GOC-Website/pull/18
